changelog:
  categories:
    - title: New Beta version
      labels:
        - '*'
    - title: Files architecture
      labels:
        - 'breaking-change'
    - title: ModelComposite to PropertiesBag
      labels:
        - 'breaking-change'
    - title: FrameRate to Framerate
      labels:
        - 'breaking-change'
    - title: FrameRates to FramerateCollection
      labels:
        - 'breaking-change'
    - title: CoreAttribute
      labels:
        - 'removed'
    - title: Add Animation facade
      labels:
        - 'added'
    - title: Add Appearance facade
      labels:
        - 'added'
    - title: Add Climbing facade
      labels:
        - 'added'
    - title: Add framerate facade
      labels:
        - 'added'